controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    xbot_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    xbot_diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

xbot_diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]

    # 轮子距离
    wheel_separation: 0.20
    #wheels_per_side: 1  # actually 2, but both are controlled by 1 signal
    # 轮子半径
    wheel_radius: 0.32

    # 轮子间距倍数
    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    # 发布数量
    publish_rate: 50.0
    # 里程计 frame id
    odom_frame_id: odom
    base_frame_id: bast_footprint
    pose_covariance_diagonal : [0.001, 0.001, 0.0, 0.0, 0.0, 0.01]
    twist_covariance_diagonal: [0.001, 0.0, 0.0, 0.0, 0.0, 0.01]

    # 是否为开环控制
    open_loop: false
    # 始能里程计 TF 发布
    enable_odom_tf: true

    # cmd vel 超时命令
    cmd_vel_timeout: 0.5
    #publish_limited_velocity: true
    #velocity_rolling_window_size: 10

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true
    linear.x.max_velocity: 1.0
    linear.x.min_velocity: -1.0
    linear.x.max_acceleration: 1.0
    linear.x.max_jerk: .NAN
    linear.x.min_jerk: .NAN

    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: true
    angular.z.max_velocity: 1.0
    angular.z.min_velocity: -1.0
    angular.z.max_acceleration: 1.0
    angular.z.min_acceleration: -1.0
    angular.z.max_jerk: .NAN
    angular.z.min_jerk: .NAN
